### ISSUE TITLE
Triplestore connection error when using dockerComposeUp

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#1122]
I can run the bulk import in #1100 without errors if I:

- use `webapi/reStart` to start Knora
- use GraphDB's `bin/graphdb` script to start GraphDB
- run Sipi in Docker

But if I start everything with `dockerComposeUp` in SBT, and then run the bulk import script, I get this error in the client:

```
{
  "status":11,
  "error":"org.knora.webapi.BadRequestException: An error occurred when requesting mapping http://rdfh.ch/standoff/mappings/StandardMapping: Failed to connect to triplestore"
}
```

and this error in the server log:

```
webapi_1_f5153ef8fb2c | [2018-12-10 14:26:17,775] ERROR - OneForOneStrategy - Failed to connect to triplestore
webapi_1_f5153ef8fb2c | org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
webapi_1_f5153ef8fb2c | 	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:249)
webapi_1_f5153ef8fb2c | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$1.applyOrElse(HttpTriplestoreConnector.scala:644)
webapi_1_f5153ef8fb2c | 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$1.applyOrElse(HttpTriplestoreConnector.scala:642)
webapi_1_f5153ef8fb2c | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
webapi_1_f5153ef8fb2c | 	at scala.util.Failure.recover(Try.scala:230)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:392)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi_1_f5153ef8fb2c | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
webapi_1_f5153ef8fb2c | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi_1_f5153ef8fb2c | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
webapi_1_f5153ef8fb2c | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
webapi_1_f5153ef8fb2c | 	at java.base/java.lang.Thread.run(Thread.java:844)
webapi_1_f5153ef8fb2c | Caused by: java.lang.IllegalStateException: Substream Source cannot be materialized more than once
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.SubSource$$anon$4.setCB(StreamOfStreams.scala:756)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.SubSource$$anon$4.preStart(StreamOfStreams.scala:766)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
webapi_1_f5153ef8fb2c | 	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
webapi_1_f5153ef8fb2c | 	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
webapi_1_f5153ef8fb2c | 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
webapi_1_f5153ef8fb2c | 	at akka.actor.ActorCell.create(ActorCell.scala:652)
webapi_1_f5153ef8fb2c | 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
webapi_1_f5153ef8fb2c | 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi_1_f5153ef8fb2c | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

However, other API requests (e.g. http://localhost:3333/admin/lists) seem to work.

In my Docker preferences (on macOS), Docker has 4 CPUs and 6 GB of memory.

**Comment by gfoo** [comment]
related to #1081 ?

**Comment by benjamingeer** [comment]
> related to #1081 ?

Maybe so. I tried `dockerComposeRestart`, but it didn't help.
