### ISSUE TITLE
Bulk import error

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1273]
This is what I'm getting as an error:

```
{"status":4,"error":"org.knora.webapi.TriplestoreResponseException: Triplestore responded with HTTP code 400: MALFORMED QUERY: Lexical error at line 570150, column 56.  Encountered: \"\\n\" (10), after : \"\\\" ;\""}
```

This is what GraphDB is saying:
```
graphdb_1  | [INFO ] 2019-03-24 09:19:45,668 [repositories/knora-test | c.o.g.s.StatementsController] POST SPARQL update request to repository
graphdb_1  | [INFO ] 2019-03-24 09:19:47,518 [repositories/knora-test | o.e.r.h.s.ProtocolExceptionResolver] Client sent bad request ( 400)
graphdb_1  | org.eclipse.rdf4j.http.server.ClientHTTPException: MALFORMED QUERY: Lexical error at line 570150, column 56.  Encountered: "\n" (10), after : "\" ;"
graphdb_1  | 	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.getSparqlUpdateResult(StatementsController.java:312)
graphdb_1  | 	at org.eclipse.rdf4j.http.server.repository.statements.StatementsController.handleRequestInternal(StatementsController.java:122)
graphdb_1  | 	at com.ontotext.graphdb.sesame.StatementsController.handleRequestInternal(StatementsController.java:26)
graphdb_1  | 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
graphdb_1  | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
graphdb_1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
graphdb_1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
graphdb_1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
graphdb_1  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
graphdb_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
graphdb_1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
graphdb_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
graphdb_1  | 	at com.ontotext.forest.core.request.RequestFilter.doFilterInternal(RequestFilter.java:41)
graphdb_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
graphdb_1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
graphdb_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
graphdb_1  | 	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
graphdb_1  | 	at com.ontotext.forest.security.AdminDelegatingFilterProxy.doFilter(AdminDelegatingFilterProxy.java:29)
graphdb_1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
graphdb_1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
graphdb_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
graphdb_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
graphdb_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
graphdb_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
graphdb_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
graphdb_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
graphdb_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
graphdb_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
graphdb_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:501)
graphdb_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
graphdb_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
graphdb_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
graphdb_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
graphdb_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
graphdb_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
graphdb_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
graphdb_1  | 	at java.lang.Thread.run(Thread.java:745)
```

Reproduction steps:
- Curl:
```
$ curl -v -u root@example.com:test --data @mls-bulk.xml --header "Content-Type: application/xml" http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0807
```
- Link to XML: https://www.dropbox.com/s/1tr2mrqzgynenpq/mls-bulk.xml?dl=1

**Comment by subotic** [comment]
Any thoughts? I guess if I was doing something wrong, then `webapi` would complain much earlier, or I'm actually doing something wrong, i.e. have funny data, and the `webapi` checks missed it.

**Comment by benjamingeer** [comment]
This is definitely a bug, but I need the ontology so I can reproduce it. Otherwise I get `Ontology not found: http://www.knora.org/ontology/0807/mls`.

**Comment by subotic** [comment]
hmm, good point. I will need a minute to generate the ontology. I will attach it to this issue.

**Comment by subotic** [comment]
and thanks :-)

**Comment by subotic** [comment]
Here is the ontology. Thanks :-)

[mls.zip](https://github.com/dhlab-basel/Knora/files/3002973/mls.zip)

**Comment by benjamingeer** [comment]
The ontology you provided doesn't contain any class or property definitions. I think you exported the named graph `<http://www.knora.org/data/0807/mls>` by mistake instead of `<http://www.knora.org/ontology/0807/mls>`.

**Comment by benjamingeer** [comment]
And it's me who should be thanking you for the bug report. :)

**Comment by subotic** [comment]
Here the updated version:
[mls.zip](https://github.com/dhlab-basel/Knora/files/3003374/mls.zip)

**Comment by benjamingeer** [comment]
It's because we're trying to insert this:

```
rdfs:label """Hämmerli, Urs "Hämi"""" 
```

I don't know why this is incorrect. I'll try to find out what we should be doing instead.

**Comment by benjamingeer** [comment]
OK, silly me, we forgot to escape quotes in `rdfs:label` in bulk imports.
