### ISSUE TITLE
Failing documentation generation

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1316]
Running `$ sbt docs/makeSite` fails with the following error:

```
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/subotic/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/Users/subotic/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading settings for project knora-build from plugins.sbt ...
[info] Loading project definition from /Users/subotic/_github.com/dhlab-basel/Knora/project
[info] Updating ProjectRef(uri("file:/Users/subotic/_github.com/dhlab-basel/Knora/project/"), "knora-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project knora from KnoraBuild.sbt ...
[info] Set current project to knora (in build file:/Users/subotic/_github.com/dhlab-basel/Knora/)
[info] building typescript documentation and graphviz diagrams...
rm -rf target/site/api-v1/*
rm -rf target/site/api-v2/*
rm -f src/paradox/faq-fig2.dot.png src/paradox/faq-fig1.dot.png src/paradox/05-internals/design/api-admin/administration-fig2.dot.png src/paradox/05-internals/design/api-admin/administration-fig3.dot.png src/paradox/05-internals/design/api-admin/administration-fig1.dot.png src/paradox/05-internals/design/api-admin/administration-fig4.dot.png src/paradox/05-internals/design/api-admin/administration-fig5.dot.png src/paradox/05-internals/design/api-admin/administration-fig6.dot.png src/paradox/02-knora-ontologies/knora-base-fig1.dot.png src/paradox/02-knora-ontologies/knora-base-fig2.dot.png src/paradox/02-knora-ontologies/knora-base-fig3.dot.png src/paradox/02-knora-ontologies/introduction-fig3.dot.png src/paradox/02-knora-ontologies/introduction-fig2.dot.png src/paradox/02-knora-ontologies/introduction-fig1.dot.png
typedoc --out target/site/api-v1 --readme none --name "Knora API V1 Format Documentation" --module commonjs ../salsah1/src/typescript_interfaces

Using TypeScript 2.3.2 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib


Documentation generated at /Users/subotic/_github.com/dhlab-basel/Knora/docs/target/site/api-v1

typedoc --out target/site/api-v2 --readme none --name "Knora API V2 JSON-LD Format Documentation" --module commonjs src/api-v2

Using TypeScript 2.3.2 from /usr/local/lib/node_modules/typedoc/node_modules/typescript/lib
Error: /Users/subotic/_github.com/dhlab-basel/Knora/docs/src/api-v2/samples/resourcesResponses.ts(5)
 Type '{ "@id": string; "@type": string; "incunabula:citation": ({ "@id": string; "@type": string; "knor...' is not assignable to type 'Resource'.
  Property '"http://www.w3.org/2000/01/rdf-schema#label"' is missing in type '{ "@id": string; "@type": string; "incunabula:citation": ({ "@id": string; "@type": string; "knor...'.
Error: /Users/subotic/_github.com/dhlab-basel/Knora/docs/src/api-v2/samples/resourcesResponses.ts(2684)
 Type '{ "@graph": ({ "@id": string; "@type": string; "incunabula:partOfValue": { "@id": string; "@type"...' is not assignable to type 'ResourcesSequence'.
  Object literal may only specify known properties, and '"@context"' does not exist in type 'ResourcesSequence'.
Error: /Users/subotic/_github.com/dhlab-basel/Knora/docs/src/api-v2/samples/resourcesResponses.ts(2694)
 Type '{ "@id": string; "@type": string; "anything:hasBoolean": { "@id": string; "@type": string; "knora...' is not assignable to type 'Resource'.
  Property '"http://www.w3.org/2000/01/rdf-schema#label"' is missing in type '{ "@id": string; "@type": string; "anything:hasBoolean": { "@id": string; "@type": string; "knora...'.
Error: /Users/subotic/_github.com/dhlab-basel/Knora/docs/src/api-v2/samples/resourcesResponses.ts(2951)
 Type '{ "@id": string; "@type": string; "incunabula:description": "Titel: \"Das andechtig zitglo(e)ggly...' is not assignable to type 'Resource'.
  Property '"http://www.w3.org/2000/01/rdf-schema#label"' is missing in type '{ "@id": string; "@type": string; "incunabula:description": "Titel: \"Das andechtig zitglo(e)ggly...'.
make: *** [jsonformattest] Error 4
[error] java.lang.IllegalStateException: typescript documentation and graphviz diagrams failed to build
[error] 	at $5371427863572dde0d6e$.$anonfun$$sbtdef$2(/Users/subotic/_github.com/dhlab-basel/Knora/KnoraBuild.sbt:156)
[error] 	at $5371427863572dde0d6e$.$anonfun$$sbtdef$2$adapted(/Users/subotic/_github.com/dhlab-basel/Knora/KnoraBuild.sbt:133)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (docs / makeSite) java.lang.IllegalStateException: typescript documentation and graphviz diagrams failed to build
[error] Total time: 6 s, completed May 3, 2019 2:19:20 PM
[INFO] [05/03/2019 14:19:20.446] [Thread-26] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

**Comment by subotic** [comment]
@benjamingeer you seem to have commented out documentation building on Travis in this [commit](https://github.com/dhlab-basel/Knora/commit/5995f614cec04aefc64d996eb4e8c4d688bfe2a8#diff-354f30a63fb0907d4ad57269548329e3). So do you maybe know what you did when the typescript checking stuff broke?

**Comment by benjamingeer** [comment]
> @benjamingeer you seem to have commented out documentation building on Travis in this commit.

I did that because one of the documentation build tools couldn’t be installed on Travis, I can’t remember which one. My home internet is down, so I won’t be able to do much else today.

> So do you maybe know what you did when the typescript checking stuff broke?

If Knora’s responses have changed, you have to change the sample responses so they match Knora’s output. Each sample has a comment above it with the URL that was used to generate it. Maybe Tobias can help more than I can today.

**Comment by subotic** [comment]
@benjamingeer don't worry. When I'm back from Portugal in two weeks, we can take a look at it.

**Comment by benjamingeer** [comment]
@tobiasschweizer Is there any chance you could give me a hand with this? I'm confused about why it's broken.
