### ISSUE TITLE
Incorrect error handling when a value in a deleted resource is requested

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#1328]
I am not sure if it is very dangerous but our log fills up with:
```
api_1_e9a49bba8d18 | org.knora.webapi.InconsistentTriplestoreDataException: entity http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA has no project
```

I am not sure of the meaning of "has no project" but it is a `Value` and values have no `knora-base:attachedToProject`.

Is it something to worry about?

If not, is it hard to remove from the logs?

**Comment by benjamingeer** [comment]
It must be a bug. Can you please post the complete stack trace so we can see where this exception is being thrown?

A Knora value isn't supposed to have `knora-base:attachedToProject`; it gets its project from its resource.

**Comment by loicjaouen** [comment]
sure:

```
ESC[32mapi_1_e9a49bba8d18 |ESC[0m org.knora.webapi.InconsistentTriplestoreDataException: entity http://rdfh.ch/0107/ylM9mB5CSB2vVt9efgyWaA/values/oQQEtQnQSZ6wr1U1_MK__Q has no project
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at org.knora.webapi.util.PermissionUtilADM$.$anonfun$getUserPermissionFromAssertionsADM$2(PermissionUtilADM.scala:316)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.collection.MapLike.getOrElse(MapLike.scala:128)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.collection.AbstractMap.getOrElse(Map.scala:59)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at org.knora.webapi.util.PermissionUtilADM$.getUserPermissionFromAssertionsADM(PermissionUtilADM.scala:316)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at org.knora.webapi.responders.admin.SipiResponderADM.$anonfun$getFileInfoForSipiADM$3(SipiResponderADM.scala:95)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.util.Success.$anonfun$map$1(Try.scala:251)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.util.Success.map(Try.scala:209)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
ESC[32mapi_1_e9a49bba8d18 |ESC[0m       at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by benjamingeer** [comment]
Does the resource that contains the value have `knora-base:attachedToProject`?

**Comment by benjamingeer** [comment]
Actually could you run these three SPARQL queries in the GraphDB workbench, and post the results:

1. (please post as Turtle)

```sparql
CONSTRUCT { ?resource ?p ?o }
FROM <http://www.ontotext.com/explicit>
WHERE {
    BIND(<http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg> as ?resource)
    ?resource ?p ?o .
}
```

2. (please post as Turtle)

```sparql
CONSTRUCT { ?value ?p ?o }
FROM <http://www.ontotext.com/explicit>
WHERE {
    BIND(<http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA> as ?value)
    ?value ?p ?o .
}
```

3. (please post as CSV)

```sparql
SELECT ?fileValue ?objPred ?objObj
WHERE {
    BIND(<http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA> as ?fileValue)

    ?fileValue knora-base:isDeleted false .

    {
        GRAPH <http://www.ontotext.com/explicit> {
            ?fileValue ?objPred ?objObj .
        }

        FILTER(?objPred != knora-base:attachedToProject)
    }
    UNION
    {
        ?resource knora-base:hasFileValue ?fileValue ;
            knora-base:isDeleted false ;
            knora-base:attachedToProject ?resourceProject .

        BIND(knora-base:attachedToProject AS ?objPred)
        BIND(?resourceProject AS ?objObj)
    }
}
```

**Comment by loicjaouen** [comment]
thanks for looking into it :)

1. base resource

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sesame: <http://www.openrdf.org/schema/sesame#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix fn: <http://www.w3.org/2005/xpath-functions#> .

<http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg> a <http://www.knora.org/ontology/0107/stardom#Page> ;
	rdfs:label "A_100-1-A4_1_406 p. 405" ;
	<http://www.knora.org/ontology/knora-base#isDeleted> "true"^^xsd:boolean ;
	<http://www.knora.org/ontology/knora-base#attachedToProject> <http://rdfh.ch/projects/0107> ;
	<http://www.knora.org/ontology/knora-base#hasStillImageFileValue> <http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA> ;
	<http://www.knora.org/ontology/knora-base#creationDate> "2019-04-26T16:44:17.485Z"^^xsd:dateTime ;
	<http://www.knora.org/ontology/knora-base#deleteDate> "2019-05-22T21:21:00.507685Z"^^xsd:dateTime ;
	<http://www.knora.org/ontology/knora-base#lastModificationDate> "2019-05-22T21:21:00.507685Z"^^xsd:dateTime ;
	<http://www.knora.org/ontology/knora-base#hasPermissions> "CR knora-base:ProjectAdmin|D knora-base:Creator|M http://rdfh.ch/groups/0107/stardom-snf-team|V http://rdfh.ch/groups/0107/stardom-student|RV http://rdfh.ch/groups/0107/stardom-researcher" ;
	<http://www.knora.org/ontology/knora-base#attachedToUser> <http://rdfh.ch/users/stardom-import-snf> ;
	<http://www.knora.org/ontology/0107/stardom#hasPageSeqnum> <http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/9oxqG0_bQYe4trZ94sqoMw> ;
	<http://www.knora.org/ontology/0107/stardom#isPartOfDocumentPiece> <http://rdfh.ch/0107/NKiXGRHDRa-Rfj3ncRsAKA> ;
	<http://www.knora.org/ontology/0107/stardom#isPartOfDocumentPieceValue> <http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/7jLETLnrQAqD2MWiUMPegw> ;
	<http://www.knora.org/ontology/knora-base#deletedBy> <http://rdfh.ch/users/stardom-aboillat> .
```

2. the value:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sesame: <http://www.openrdf.org/schema/sesame#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix fn: <http://www.w3.org/2005/xpath-functions#> .

<http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA> a <http://www.knora.org/ontology/knora-base#StillImageFileValue> ;
	<http://www.knora.org/ontology/knora-base#isDeleted> "false"^^xsd:boolean ;
	<http://www.knora.org/ontology/knora-base#dimX> "3526"^^xsd:integer ;
	<http://www.knora.org/ontology/knora-base#dimY> "4219"^^xsd:integer ;
	<http://www.knora.org/ontology/knora-base#internalFilename> "9hxmmrWh0a7-CnRCq0650ro.jpx" ;
	<http://www.knora.org/ontology/knora-base#internalMimeType> "image/jp2" ;
	<http://www.knora.org/ontology/knora-base#originalFilename> "A_100-1-A4_1_406.JPG" ;
	<http://www.knora.org/ontology/knora-base#originalMimeType> "image/jpeg" ;
	<http://www.knora.org/ontology/knora-base#valueCreationDate> "2019-04-26T16:44:17.485Z"^^xsd:dateTime ;
	<http://www.knora.org/ontology/knora-base#valueHasOrder> "0"^^xsd:integer ;
	<http://www.knora.org/ontology/knora-base#valueHasString> "A_100-1-A4_1_406.JPG" ;
	<http://www.knora.org/ontology/knora-base#hasPermissions> "CR knora-base:ProjectAdmin|D knora-base:Creator|M http://rdfh.ch/groups/0107/stardom-snf-team|V http://rdfh.ch/groups/0107/stardom-student|RV http://rdfh.ch/groups/0107/stardom-researcher" ;
	<http://www.knora.org/ontology/knora-base#attachedToUser> <http://rdfh.ch/users/stardom-import-snf> .
```

3. the value again, because the resource is deleted (which I missed to see before):

```
fileValue,objPred,objObj
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://www.knora.org/ontology/knora-base#StillImageFileValue
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#isDeleted,false
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#dimX,3526
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#dimY,4219
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#internalFilename,9hxmmrWh0a7-CnRCq0650ro.jpx
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#internalMimeType,image/jp2
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#originalFilename,A_100-1-A4_1_406.JPG
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#originalMimeType,image/jpeg
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#valueCreationDate,2019-04-26T16:44:17.485Z
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#valueHasOrder,0
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#valueHasString,A_100-1-A4_1_406.JPG
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#hasPermissions,CR knora-base:ProjectAdmin|D knora-base:Creator|M http://rdfh.ch/groups/0107/stardom-snf-team|V http://rdfh.ch/groups/0107/stardom-student|RV http://rdfh.ch/groups/0107/stardom-researcher
http://rdfh.ch/0107/gjs0RTRkTZeYDT_37nbcCg/values/Dy-pWIujTIqdqKqrswwqfA,http://www.knora.org/ontology/knora-base#attachedToUser,http://rdfh.ch/users/stardom-import-snf
```

**Comment by benjamingeer** [comment]
OK, the bug is that you should not be able to access this value at all, because the resource is deleted. You should instead get an HTTP 404 Not Found error.

**Comment by benjamingeer** [comment]
It also seems a bit strange that you're getting requests for values in deleted resources. Normally a deleted resource should be invisible, so nobody would even know it's there.
