### ISSUE TITLE
The startup ends in a thrown exception if the triplestore is not up-to-date

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#1373]
The expected behavior would be either:

1. retry checks continuously thus giving the user the possibility to do what is needed to fix the problem and then resume once the problem is fixed, or
2. come to an orderly stop

```
webapi [INFO ] [2019-07-10 10:01:59,470] [HttpTriplestoreConnector(akka://webapi)] [200] GraphDB Query took: 27ms
webapi [ERROR] [2019-07-10 10:01:59,550] [Dispatcher] The knora-base ontology in the repository is not up to date. See the Knora documentation on repository updates.
webapi org.knora.webapi.InconsistentTriplestoreDataException: The knora-base ontology in the repository is not up to date. See the Knora documentation on repository updates.
webapi 	at org.knora.webapi.responders.v2.OntologyResponderV2.$anonfun$loadOntologies$7(OntologyResponderV2.scala:140)
webapi 	at scala.Option.getOrElse(Option.scala:138)
webapi 	at org.knora.webapi.responders.v2.OntologyResponderV2.$anonfun$loadOntologies$5(OntologyResponderV2.scala:140)
webapi 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
webapi 	at scala.util.Success.map(Try.scala:213)
webapi 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
webapi 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
webapi 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
webapi 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
webapi 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
webapi 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
webapi [ERROR] [2019-07-10 10:01:59,555] [OneForOneStrategy] ApplicationStateActor received an unexpected message Failure(org.knora.webapi.InconsistentTriplestoreDataException: The knora-base ontology in the repository is not up to date. See the Knora documentation on repository updates.) of type akka.actor.Status.Failure
webapi org.knora.webapi.UnexpectedMessageException: ApplicationStateActor received an unexpected message Failure(org.knora.webapi.InconsistentTriplestoreDataException: The knora-base ontology in the repository is not up to date. See the Knora documentation on repository updates.) of type akka.actor.Status.Failure
webapi 	at org.knora.webapi.app.ApplicationStateActor$$anonfun$receive$1.applyOrElse(ApplicationStateActor.scala:153)
webapi 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
webapi 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
webapi 	at org.knora.webapi.app.ApplicationStateActor.akka$actor$Timers$$super$aroundReceive(ApplicationStateActor.scala:20)
webapi 	at akka.actor.Timers.aroundReceive(Timers.scala:55)
webapi 	at akka.actor.Timers.aroundReceive$(Timers.scala:40)
webapi 	at org.knora.webapi.app.ApplicationStateActor.aroundReceive(ApplicationStateActor.scala:20)
webapi 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
webapi 	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
webapi 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
webapi 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
webapi 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by benjamingeer** [comment]
I think an orderly stop would make more sense. But what should a responder do to make Knora shut down?

**Comment by benjamingeer** [comment]
Discussion with @subotic:

Refactor `KnoraService` to move most of its functionality into `ApplicationStateActor`, which can then receive shutdown and reload messages.
