### ISSUE TITLE
Problem with interval value

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#1399]
When I try to fetch http://0.0.0.0:3333/v2/resources/http%3A%2F%2Frdfh.ch%2F0001%2FH6gBWUuJSuuO-CilHV8kQw (anything "testding")  I get an error:

```
{
"knora-api:error": "org.knora.webapi.InconsistentTriplestoreDataException: Unexpected object of http://rdfh.ch/0001/H6gBWUuJSuuO-CilHV8kQw/values/RbDKPKHWTC-0lkRKae-E6A http://www.knora.org/ontology/knora-base#valueHasIntervalStart: 0",
"@context": {
"knora-api": "http://api.knora.org/ontology/knora-api/v2#"
}
}
```

Knora output: 

```
2019-08-26 11:39:30 | ERROR | KnoraExceptionHandler$ | Unable to run route /v2/resources/http:%2F%2Frdfh.ch%2F0001%2FH6gBWUuJSuuO-CilHV8kQw
webapi org.knora.webapi.InconsistentTriplestoreDataException: Unexpected object of http://rdfh.ch/0001/H6gBWUuJSuuO-CilHV8kQw/values/RbDKPKHWTC-0lkRKae-E6A http://www.knora.org/ontology/knora-base#valueHasIntervalStart: 0
webapi 	at org.knora.webapi.util.ConstructResponseUtilV2$RdfData.$anonfun$maybeDecimalObject$2(ConstructResponseUtilV2.scala:209)
webapi 	at org.knora.webapi.messages.store.triplestoremessages.LiteralV2.asDecimalLiteral(TriplestoreMessages.scala:488)
webapi 	at org.knora.webapi.messages.store.triplestoremessages.LiteralV2.asDecimalLiteral$(TriplestoreMessages.scala:485)
webapi 	at org.knora.webapi.messages.store.triplestoremessages.IntLiteralV2.asDecimalLiteral(TriplestoreMessages.scala:633)
webapi 	at org.knora.webapi.util.ConstructResponseUtilV2$RdfData.$anonfun$maybeDecimalObject$1(ConstructResponseUtilV2.scala:209)
webapi 	at scala.Option.map(Option.scala:163)

```

Could this be related to #1367?

**Comment by tobiasschweizer** [comment]
just an idea: maybe the value "0" is regarded as an IntLiteralV2

**Comment by benjamingeer** [comment]
Yes: https://www.w3.org/TR/turtle/#abbrev

**Comment by tobiasschweizer** [comment]
I think this would fix the problem:

```
    /**
      * Returns this [[LiteralV2]] as a [[DecimalLiteralV2]].
      *
      * @param errorFun a function that throws an exception. It will be called if this [[LiteralV2]] is not
      *                 a [[DecimalLiteralV2]].
      * @return a [[DecimalLiteralV2]].
      */
    def asDecimalLiteral(errorFun: => Nothing): DecimalLiteralV2 = {
        this match {
            case decimalLiteral: DecimalLiteralV2 => decimalLiteral
            case intLiteral: IntLiteralV2 => DecimalLiteralV2(intLiteral.value)
            case _ => errorFun
        }
    }
```

I could make a PR with that and provide a test case.

**Comment by benjamingeer** [comment]
Decimal values shouldn't be stored as integers. The bug is in the (handwritten) test data. Fixed in #1400.

**Comment by tobiasschweizer** [comment]
I understand. So the types are already handled correctly when creating date using the API?

**Comment by benjamingeer** [comment]
Thanks for asking, I've just noticed that this depends on how the number was submitted:

```
scala> new BigDecimal("5.0").toString
res1: String = 5.0

scala> new BigDecimal("5").toString
res2: String = 5
```

So we have been doing this wrong since v1.
