### ISSUE TITLE
Store Route Test  "if startup flag is not" set fails sometimes 

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#239]
The store route test "if startup flag is not set" fails sometimes without an obvious reason (the next time you run the tests it may pass although you have not made any changes):

```
[info] StoreRouteV1E2ESpec:

[info] The ResetTriplestoreContent Route ('v1/store/ResetTriplestoreContent')

=>>

=>>true

=>>true

[info] - should succeed with resetting if startup flag is set (10 seconds, 81 milliseconds)

[info] - should fail with resetting if startup flag is not set *** FAILED *** (10 seconds, 15 milliseconds)

[info]   200 OK did not equal 403 Forbidden (StoreRouteV1E2ESpec.scala:114)

[info]   org.scalatest.exceptions.TestFailedException:

[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)

[info]   at org.knora.webapi.e2e.E2ESpec.newAssertionFailedException(E2ESpec.scala:32)

[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)

[info]   at org.knora.webapi.e2e.v1.StoreRouteV1E2ESpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply$mcV$sp(StoreRouteV1E2ESpec.scala:114)

[info]   at org.knora.webapi.e2e.v1.StoreRouteV1E2ESpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(StoreRouteV1E2ESpec.scala:112)

[info]   at org.knora.webapi.e2e.v1.StoreRouteV1E2ESpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply(StoreRouteV1E2ESpec.scala:112)

[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)

[info]   at spray.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:55)

[info]   at spray.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:55)

[info]   at spray.testkit.RouteResultComponent$RouteResult.$tilde$greater(RouteResultComponent.scala:113)

[info]   at org.knora.webapi.e2e.v1.StoreRouteV1E2ESpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(StoreRouteV1E2ESpec.scala:112)

[info]   at org.knora.webapi.e2e.v1.StoreRouteV1E2ESpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(StoreRouteV1E2ESpec.scala:109)

[info]   at org.knora.webapi.e2e.v1.StoreRouteV1E2ESpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(StoreRouteV1E2ESpec.scala:109)

[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)

[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)

[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)

[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)

[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)

[info]   at org.knora.webapi.e2e.E2ESpec.withFixture(E2ESpec.scala:32)

[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)

[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)

[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)

[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)

[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)

[info]   at org.knora.webapi.e2e.E2ESpec.runTest(E2ESpec.scala:32)

[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)

[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)

[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)

[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)

[info]   at scala.collection.immutable.List.foreach(List.scala:381)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)

[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)

[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)

[info]   at scala.collection.immutable.List.foreach(List.scala:381)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)

[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)

[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)

[info]   at org.knora.webapi.e2e.E2ESpec.runTests(E2ESpec.scala:32)

[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)

[info]   at org.knora.webapi.e2e.E2ESpec.org$scalatest$BeforeAndAfterAll$$super$run(E2ESpec.scala:32)

[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)

[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)

[info]   at org.knora.webapi.e2e.E2ESpec.org$scalatest$WordSpecLike$$super$run(E2ESpec.scala:32)

[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)

[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)

[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)

[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)

[info]   at org.knora.webapi.e2e.E2ESpec.run(E2ESpec.scala:32)

[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)

[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)

[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)

[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)

[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by subotic** [comment]
Yes, there seems to be a timing issue here, but I don't know why. At that time I tried to solve it by adding waiting statements, which didn't work. Also, it only happens to me on my local machine and not on Travis. It has probably to do something with concurrency and number of CPU cores available (locally 16 and on travis only 2 cores). I will try to rewrite the test in a different way.

**Comment by benjamingeer** [comment]
It happens on Travis, too: https://travis-ci.org/dhlab-basel/Knora/builds/146381808

**Comment by subotic** [comment]
I didn't experience this in a long time. I assume it's not an issue anymore.
