### ISSUE TITLE
annoying time-out exception message in Salsah_1.5 log

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#485]
@tobiasschweizer mentions this to be annoying in #483 

```
salsah [ERROR] [04/18/2017 10:09:59.850] [salsah-system-akka.actor.default-dispatcher-72] [ActorSystem(salsah-system)] Outgoing response stream error
salsah java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
salsah 	at akka.stream.impl.Timers$IdleBidi$$anon$4.onTimer(Timers.scala:145)
salsah 	at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:939)
salsah 	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:929)
salsah 	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:929)
salsah 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:357)
salsah 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
salsah 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:292)
salsah 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
salsah 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
salsah 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
salsah 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
salsah 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
salsah 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
salsah 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
salsah 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
salsah 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by tobiasschweizer** [comment]
I could also point out more things that annoy me :-)

**Comment by loicjaouen** [comment]
no doubt ;)
