### ISSUE TITLE
Knora-Sipi performance issue

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Knora#512]
Creating a resource with a linked image takes about 3 seconds.

Talking with Ben, we agreed that I would make a test case in [SipiV1ITSpec](https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/it/scala/org/knora/webapi/e2e/v1/SipiV1ITSpec.scala).

But looking closer at it, the test case is already there: `"create an 'incunabula:page' with parameters"`.

**Comment by loicjaouen** [comment]
adding some time stamp printouts to make sure 15c6b242e2edf497823b841a3f7e6b82134c338c
here is the output:

```
#### start: 1496045400897
#### before sipi send: 1496045400907, elapsed: 10
#### after sipi send: 1496045402862, elapsed: 1965, sipi upload: 1955
#### after sipi preview: 1496045402873, elapsed: 1976, sipi preview: 11
#### before knora call: 1496045402876, elapsed: 1979, preparation: 3
#### after knora call: 1496045405631, elapsed: 4734, preparation: 2755
```

From the point of view of this test;
- the first 1'955 ms are spend by sipi uploading the image, making a thumbnail and giving back the preview URL
- knora creation of the incunabula page takes another 2'755 ms

**Comment by loicjaouen** [comment]
Note: to run just one test, in intellij idea, one can right click on the test name (the line: `"create an 'incunabula:page' with parameters" in {`) and run only this one :)

Setting up VisualVM according to @benjamingeer [instructions](http://www.knora.org/documentation/manual/rst/knora-api-server/development/intellij-config.html?highlight=visualvm#profile-knora-using-visualvm-in-intellij)

Now, when running this test with VisualVM plugged in, you have to put a break point at the beginning of the test to have time to turn on the profiler in VisualVM.

Then keep the test rolling, but the profiler stops the execution with the message:

```
Profiler Agent Error: with message: Redefinition failed with error 62
Check JVMTI documentation for this error code.
```

This is overcome with this setting (from [this post](https://stackoverflow.com/questions/26834651/redefinition-failed-with-error-62-while-trying-to-profile-an-application)):
![capture d ecran 2017-05-29 a 10 56 38](https://cloud.githubusercontent.com/assets/3933654/26543348/fd166196-445d-11e7-81e8-37f966a47652.png)

When the process ends, VisualVM proposes to create the snapshot.

**Comment by loicjaouen** [comment]
But the process ended because of a time-out exception:

```
Futures timed out after [15 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [15 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:123)
	at org.knora.webapi.ITSpec.singleAwaitingRequest(ITSpec.scala:67)
	at org.knora.webapi.ITSpec.getResponseString(ITSpec.scala:71)
	at org.knora.webapi.ITSpec.getResponseJson(ITSpec.scala:83)
	at org.knora.webapi.e2e.v1.SipiV1ITSpec.$anonfun$new$6(SipiV1ITSpec.scala:217)
```

So the test didn't run and the snapshot is meaningless.

**Comment by loicjaouen** [comment]
@benjamingeer would you mind giving it a try on your set-up?

**Comment by benjamingeer** [comment]
I can't reproduce this problem:

```
[info] - should change an 'incunabula:page' with binary data (677 milliseconds)
#### start: 1496054984868
#### before sipi send: 1496054984868, elapsed: 0
#### after sipi send: 1496054984941, elapsed: 73, sipi upload: 73
#### after sipi preview: 1496054984946, elapsed: 78, sipi preview: 5
#### before knora call: 1496054984946, elapsed: 78, preparation: 0
#### after knora call: 1496054985405, elapsed: 537, preparation: 459
```

**Comment by loicjaouen** [comment]
amazing... I guess it is good news, but I am quite of clue :(  
I get the same kind of latencies on different installs, my local machine running on SSD as well as servers both on SSD and NAS.  

You build and run knora and sipi as described in the docs I guess, with `./build/sipi --config config/sipi.knora-config.lua` ?

**Comment by benjamingeer** [comment]
> You build and run knora and sipi as described in the docs I guess, with `./build/sipi --config config/sipi.knora-config.lua` ?

Yes, that's right.

**Comment by loicjaouen** [comment]
could you also run (in webapi):
```
time curl -v -i -X POST -H "Content-Type: multipart/form-data" --form "file=@_test_data/test_route/images/Chlaus.jpg" http://localhost:1024/make_thumbnail
```

and compare with the time it takes here:
```
real	0m1.084s
user	0m0.004s
sys	0m0.008s
```

**Comment by benjamingeer** [comment]
I got:

```
real	0m1.101s
user	0m0.039s
sys	0m0.006s
```

**Comment by loicjaouen** [comment]
So it takes curl 1 second and scala-test post takes 73 ms?

**Comment by benjamingeer** [comment]
I haven't a clue. Since the test with curl doesn't need Knora, could you open an issue under https://github.com/dhlab-basel/Sipi/issues with that example, and assign it to @lrosenth ?

**Comment by loicjaouen** [comment]
and why not on `curl` mailing list ;)  
asking them why http post in curl is 10 times more slow than a http post using `akka.http`  
more seriously curl was just used as a benchmark to see if your sipi set-up was that much faster than mine.

But yes, the problem might be on sipi's side.

**Comment by benjamingeer** [comment]
Akka uses [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding), but telling curl to do the same doesn't make any difference:

```
time curl -v -i -X POST --header "Transfer-Encoding: chunked" -H "Content-Type: multipart/form-data" --form "file=@_test_data/test_route/images/Chlaus.jpg" http://localhost:1024/make_thumbnail

real	0m1.120s
user	0m0.038s
sys	0m0.008s
```

**Comment by loicjaouen** [comment]
doing this test once more (and then a couple of times):

```
#### start: 1497453742882
#### before sipi send: 1497453742882, elapsed: 0
#### after sipi send: 1497453742961, elapsed: 79, sipi upload: 79
#### after sipi preview: 1497453742965, elapsed: 83, sipi preview: 4
#### before knora call: 1497453742965, elapsed: 83, preparation: 0
#### after knora call: 1497453743474, elapsed: 592, preparation: 509
```

blazing fast, matching the figures Ben had...

Let's hurry on the gui to check those nice response times: creating a resource in knora once the picture has been uploaded to sipi takes again 2.5s .

Let's be consistant with the test and create a incunabula page: 3.8s

Would there be a difference between the test and the gui?

Plugging in debug logging
