### ISSUE TITLE
Integration tests fail for DrawingsGodsV1ITSpec with GraphDb Free docker

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/Knora#652]
GraphDb Docker aborts during this test

```
[info] DrawingsGodsV1ITSpec:
[2017-10-26 18:14:55,155] INFO  - DrawingsGodsV1ITSpec - ResponderManager ready: - 
[2017-10-26 18:14:55,164] INFO  - DrawingsGodsV1ITSpec - StoreManager ready: InitializedResponse(true)
[2017-10-26 18:14:55,164] INFO  - DrawingsGodsV1ITSpec - ActorSystem IntegrationTests started
[2017-10-26 18:14:56,655] INFO  - HttpTriplestoreConnector - Connection OK: 2359
[2017-10-26 18:15:03,574] ERROR - Dispatcher - Failed to connect to triplestore
org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:209)
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:440)
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:438)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:390)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:329)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:327)
	at akka.stream.impl.fusing.Collect$$anon$2.$anonfun$wrappedPf$1(Ops.scala:208)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:169)
	at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:210)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	... 4 common frames omitted
[2017-10-26 18:15:03,575] ERROR - Dispatcher - Failed to connect to triplestore
org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:209)
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:440)
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:438)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:390)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:329)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:327)
	at akka.stream.impl.fusing.Collect$$anon$2.$anonfun$wrappedPf$1(Ops.scala:208)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:169)
	at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:210)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	... 4 common frames omitted
[2017-10-26 18:15:03,582] ERROR - PoolMasterActor - connection pool for PoolGateway(hcps = HostConnectionPoolSetup(localhost,7200,ConnectionPoolSetup(ConnectionPoolSettings(1024,0,0,2048,2,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.7),10 seconds,Duration.Inf,512,None,<function0>,List(),ParserSettings(2048,16,1024,64,8192,64,8388608,256,2097152,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,akka.stream.impl.ConstantFun$$$Lambda$378/780005519@a86a641,akka.stream.impl.ConstantFun$$$Lambda$378/780005519@a86a641,akka.stream.impl.ConstantFun$$$Lambda$379/959978710@2e91001b)),TCPTransport(None,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.7),10 seconds,Duration.Inf,512,None,<function0>,List(),ParserSettings(2048,16,1024,64,8192,64,8388608,256,2097152,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,akka.stream.impl.ConstantFun$$$Lambda$378/780005519@a86a641,akka.stream.impl.ConstantFun$$$Lambda$378/780005519@a86a641,akka.stream.impl.ConstantFun$$$Lambda$379/959978710@2e91001b)))),akka.http.scaladsl.HttpConnectionContext$@4192ded7,akka.event.MarkerLoggingAdapter@51b0395b))) has shut down unexpectedly
[DEBUG] [10/26/2017 18:15:03.582] [IntegrationTests-akka.actor.default-dispatcher-17] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [10/26/2017 18:15:03.582] [IntegrationTests-akka.actor.default-dispatcher-17] [EventStream] all default loggers stopped
[info] org.knora.webapi.other.v1.DrawingsGodsV1ITSpec *** ABORTED *** (8 seconds, 420 milliseconds)
[info]   org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
[info]   at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:209)
[info]   at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:440)
[info]   at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:438)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
[info]   at scala.util.Failure.recover(Try.scala:230)
[info]   at scala.concurrent.Future.$anonfun$recover$1(Future.scala:390)
[info]   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[info]   at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
[info]   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info]   Cause: akka.http.scaladsl.model.EntityStreamException: Entity stream truncation
[info]   at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:329)
[info]   at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:327)
[info]   at akka.stream.impl.fusing.Collect$$anon$2.$anonfun$wrappedPf$1(Ops.scala:208)
[info]   at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:169)
[info]   at akka.stream.impl.fusing.Collect$$anon$2.onPush(Ops.scala:210)
[info]   at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
[info]   at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710)
[info]   at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
[info]   at akka.actor.Actor.aroundReceive(Actor.scala:502)
[info]   at akka.actor.Actor.aroundReceive$(Actor.scala:500)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
[info]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info]   at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info]   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by loicjaouen** [comment]
for which PR is it?

**Comment by subotic** [comment]
I suppose on `develop`. I'm going to try it out now.

**Comment by loicjaouen** [comment]
for a local test then

**Comment by lrosenth** [comment]
Yes, develop branch!

On 27 Oct 2017, at 10:24, Ivan Subotic <notifications@github.com<mailto:notifications@github.com>> wrote:


I suppose on develop. I'm going to try it out now.

**Comment by loicjaouen** [comment]
i don't understand: if a change broke the test, from wherever it comes from, how could have it been merged in `develop`

**Comment by subotic** [comment]
@loicjaouen We are testing with `graphdb-se`. Maybe there is a problem with `graphdb-free`.

@lrosenth I suppose you are using `graphdb-free` 8.2.0 with our docker image (`dhlabbasel/graphdb-free`)?

**Comment by subotic** [comment]
For me the `DrawingsGodsV1ITSpec` is working, but another one is failing:

```
[info] KnoraSipiScriptsV1ITSpec:
Knora API Server using HTTP at http://0.0.0.0:3333.
[info] - Check if Sipi is running (1 second, 648 milliseconds)
[info] Calling Knora Sipi Scripts
[info] - should successfully call make_thumbnail.lua sipi script *** FAILED *** (121 milliseconds)
[info]   400 Bad Request did not equal 200 OK,
[info]    REQUEST: HttpRequest(HttpMethod(GET),http://localhost:1024/thumbs/JV3CkHXYNQF-FcNi33YsT6g.jpg/info.json,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1)),
[info]    RESPONSE: HttpResponse(400 Bad Request,List(Access-Control-Allow-Origin: *, Connection: close),HttpEntity.Strict(text/plain; charset=UTF-8,Bad Request: File not readable),HttpProtocol(HTTP/1.1)) (TestingUtilities.scala:57)
```

**Comment by subotic** [comment]
The `KnoraSipiScriptsV1ITSpec` fails both with `graphdb-se` and `graphdb-free`.

**Comment by lrosenth** [comment]
Yes, GraphDB-free docker image...

Am 27.10.2017 um 11:24 schrieb Ivan Subotic <notifications@github.com<mailto:notifications@github.com>>:


@loicjaouen<https://github.com/loicjaouen> We are testing with graphdb-se. Maybe there is a problem with graphdb-free.

@lrosenth<https://github.com/lrosenth> I suppose you are using graphdb-free 8.2.0 with our docker image (dhlabbasel/graphdb-free)?

**Comment by subotic** [comment]
Got the newest `sipi` Docker image. Now all tests are passing locally with `graphdb-se` and `graphdb-free`.
