### ISSUE TITLE
Error when logging in from SALSAH 1 GUI

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#823]
When trying to log in from the SALSAH 1 GUI I get an error (on branch `wip/standoff_v2_refactoring`).

route `http://localhost:3333/v1/session`

I guess something goes wrong when the submitted password is turned into a hash to compare it with the one in the db.

```
webapi[ERROR] Uncaught error from thread [webapi-akka.actor.default-dispatcher-19]: org/bouncycastle/crypto/generators/SCrypt, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[webapi]
webapi[ERROR] java.lang.NoClassDefFoundError: org/bouncycastle/crypto/generators/SCrypt
webapi[ERROR] 	at org.springframework.security.crypto.scrypt.SCryptPasswordEncoder.decodeAndCheckMatches(SCryptPasswordEncoder.java:151)
webapi[ERROR] 	at org.springframework.security.crypto.scrypt.SCryptPasswordEncoder.matches(SCryptPasswordEncoder.java:133)
webapi[ERROR] 	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.$anonfun$passwordMatch$1(UsersMessagesADM.scala:482)
webapi[ERROR] 	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.$anonfun$passwordMatch$1$adapted(UsersMessagesADM.scala:479)
webapi[ERROR] 	at scala.Option.exists(Option.scala:240)
webapi[ERROR] 	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.passwordMatch(UsersMessagesADM.scala:479)
webapi[ERROR] 	at org.knora.webapi.routing.Authenticator$.authenticateCredentialsV2(Authenticator.scala:360)
webapi[ERROR] 	at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$getUserADMThroughCredentialsV2(Authenticator.scala:552)
webapi[ERROR] 	at org.knora.webapi.routing.Authenticator.doLoginV1(Authenticator.scala:74)
webapi[ERROR] 	at org.knora.webapi.routing.Authenticator.doLoginV1$(Authenticator.scala:68)
webapi[ERROR] 	at org.knora.webapi.routing.v1.AuthenticationRouteV1$.doLoginV1(AuthenticationRouteV1.scala:35)
webapi[ERROR] 	at org.knora.webapi.routing.v1.AuthenticationRouteV1$.$anonfun$knoraApiPath$8(AuthenticationRouteV1.scala:67)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:59)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:41)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi[ERROR] 	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:59)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi[ERROR] 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi[ERROR] 	at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
webapi[ERROR] 	at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
webapi[ERROR] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
webapi[ERROR] 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
webapi[ERROR] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
webapi[ERROR] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
webapi[ERROR] 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
webapi[ERROR] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
webapi[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
webapi[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
webapi[ERROR] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
webapi[ERROR] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
webapi[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
webapi[ERROR] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
webapi[ERROR] 	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:559)
webapi[ERROR] 	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
webapi[ERROR] 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
webapi[ERROR] 	at akka.kamon.instrumentation.ActorMonitors$$anon$1.$anonfun$processMessage$1(ActorMonitor.scala:123)
webapi[ERROR] 	at kamon.Kamon$.withContext(Kamon.scala:120)
webapi[ERROR] 	at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:123)
webapi[ERROR] 	at akka.kamon.instrumentation.ActorMonitors$TracedMonitor.processMessage(ActorMonitor.scala:81)
webapi[ERROR] 	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
webapi[ERROR] 	at akka.actor.ActorCell.invoke(ActorCell.scala:552)
webapi[ERROR] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
webapi[ERROR] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
webapi[ERROR] 	at kamon.executors.Executors$InstrumentedExecutorService$$anon$7.run(Executors.scala:270)
webapi[ERROR] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
webapi[ERROR] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi[ERROR] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi[ERROR] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi[ERROR] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
webapi[ERROR] Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.generators.SCrypt
webapi[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
webapi[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
webapi[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
webapi[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
webapi[ERROR] 	... 90 more
webapi [2018-04-12 12:16:30,028] ERROR - ActorSystemImpl - Uncaught error from thread [webapi-akka.actor.default-dispatcher-19]: org/bouncycastle/crypto/generators/SCrypt, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[webapi]
webapi java.lang.NoClassDefFoundError: org/bouncycastle/crypto/generators/SCrypt
webapi 	at org.springframework.security.crypto.scrypt.SCryptPasswordEncoder.decodeAndCheckMatches(SCryptPasswordEncoder.java:151)
webapi 	at org.springframework.security.crypto.scrypt.SCryptPasswordEncoder.matches(SCryptPasswordEncoder.java:133)
webapi 	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.$anonfun$passwordMatch$1(UsersMessagesADM.scala:482)
webapi 	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.$anonfun$passwordMatch$1$adapted(UsersMessagesADM.scala:479)
webapi 	at scala.Option.exists(Option.scala:240)
webapi 	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.passwordMatch(UsersMessagesADM.scala:479)
webapi 	at org.knora.webapi.routing.Authenticator$.authenticateCredentialsV2(Authenticator.scala:360)
webapi 	at org.knora.webapi.routing.Authenticator$.org$knora$webapi$routing$Authenticator$$getUserADMThroughCredentialsV2(Authenticator.scala:552)
webapi 	at org.knora.webapi.routing.Authenticator.doLoginV1(Authenticator.scala:74)
webapi 	at org.knora.webapi.routing.Authenticator.doLoginV1$(Authenticator.scala:68)
webapi 	at org.knora.webapi.routing.v1.AuthenticationRouteV1$.doLoginV1(AuthenticationRouteV1.scala:35)
webapi 	at org.knora.webapi.routing.v1.AuthenticationRouteV1$.$anonfun$knoraApiPath$8(AuthenticationRouteV1.scala:67)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:59)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi 	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:41)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi 	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
webapi 	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
webapi 	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
webapi 	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$1(RouteConcatenation.scala:44)
webapi 	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:59)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:65)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
webapi 	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:152)
webapi 	at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:86)
webapi 	at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
webapi 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
webapi 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
webapi 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
webapi 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
webapi 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
webapi 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
webapi 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
webapi 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
webapi 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
webapi 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
webapi 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
webapi 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
webapi 	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:559)
webapi 	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
webapi 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
webapi 	at akka.kamon.instrumentation.ActorMonitors$$anon$1.$anonfun$processMessage$1(ActorMonitor.scala:123)
webapi 	at kamon.Kamon$.withContext(Kamon.scala:120)
webapi 	at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:123)
webapi 	at akka.kamon.instrumentation.ActorMonitors$TracedMonitor.processMessage(ActorMonitor.scala:81)
webapi 	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
webapi 	at akka.actor.ActorCell.invoke(ActorCell.scala:552)
webapi 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
webapi 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
webapi 	at kamon.executors.Executors$InstrumentedExecutorService$$anon$7.run(Executors.scala:270)
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
webapi Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.generators.SCrypt
webapi 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
webapi 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
webapi 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
webapi 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
webapi 	... 90 common frames omitted
webapi ... finished with exit code 255
```

**Comment by subotic** [comment]
@tobiasschweizer fix is in `develop`

**Comment by subotic** [comment]
@tobiasschweizer if you cannot merge the whole branch, then you can cherrypick this commit 239bd004f2b649b3d7f607f9c4abec6462b03a1b

**Comment by tobiasschweizer** [comment]
@subitoc Ok, merged `develop` in my branch and i works :-)

Thanks!
