### ISSUE TITLE
Travis build failure when generating Sphinx docs

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#837]
https://travis-ci.org/dhlab-basel/Knora/jobs/373013256

```
[info] Generating Sphinx html documentation...
[error] /home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated eventmachine 1.2.6, but your Gemfile requires eventmachine 1.2.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:31:in `block in setup'
[error] 	from /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
[error] 	from /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:26:in `map'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:26:in `setup'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/gems/jekyll-3.8.0/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/gems/jekyll-3.8.0/exe/jekyll:11:in `<top (required)>'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/bin/jekyll:23:in `load'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/bin/jekyll:23:in `<main>'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
[error] 	from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

Also, there are these warnings:

```
[warn] /home/travis/build/dhlab-basel/Knora/docs/src/sphinx/02-knora-ontologies/salsah-gui.rst:77: WARNING: Pygments lexer name 'ebnf' is not known
[warn] /home/travis/build/dhlab-basel/Knora/docs/src/sphinx/03-knora-api-server/api_v2/ontology-information.rst:51: WARNING: Pygments lexer name 'jsonld' is not known
```

We currently use the `ebnf` and `jsonld` lexers in RST. I think upgrading to a more recent version of Sphinx might fix this.

**Comment by benjamingeer** [comment]
Works now after merging from develop.

**Comment by subotic** [comment]
yes, had the same issue and added a fix :-)

**Comment by benjamingeer** [comment]
Thank you!
