### ISSUE TITLE
sbt stage fails

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#855]
SBT `stage` fails on branch `wip/ontology-doc-formats` (PR #851) since I added a dependency on `rdf4j-runtime` to `WebapiBuild.sbt`:

```
[error] 34 errors were encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/aop/Advice.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/aop/Advice.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/aop/AspectException.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/aop/AspectException.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/ConstructorInterceptor.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/ConstructorInterceptor.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/ConstructorInvocation.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/ConstructorInvocation.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/Interceptor.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/Interceptor.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/Invocation.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/Invocation.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/Joinpoint.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/Joinpoint.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/MethodInterceptor.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/MethodInterceptor.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/MethodInvocation.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/MethodInvocation.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/MergeReaderWrapper.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/MergeReaderWrapper.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$1.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$1.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$2.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$2.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$3.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$3.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$DocComparator.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$DocComparator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$DocMap.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$DocMap.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$DocValueSorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$DocValueSorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingBinaryDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingBinaryDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingBits.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingBits.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum$DocFreqSorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum$DocFreqSorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingFields.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingFields.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingNumericDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingNumericDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum$DocOffsetSorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum$DocOffsetSorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedNumericDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedNumericDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedSetDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedSetDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingTerms.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingTerms.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingTermsEnum.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingTermsEnum.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector$1.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector$1.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.6.jar:org/joda/time/base/BaseDateTime.class
[error] /Users/benjamingeer/.ivy2/cache/org.elasticsearch/elasticsearch/jars/elasticsearch-2.4.6.jar:org/joda/time/base/BaseDateTime.class
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:141)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:84)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error] 	at sbtassembly.Assembly$$$Lambda$11768/1841055797.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$587/1833973673.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1819/955994360.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$1836/675362546.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$1827/866699721.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1834/1075314220.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (assembly) deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/aop/Advice.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/aop/Advice.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/aop/AspectException.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/aop/AspectException.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/ConstructorInterceptor.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/ConstructorInterceptor.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/ConstructorInvocation.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/ConstructorInvocation.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/Interceptor.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/Interceptor.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/Invocation.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/Invocation.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/Joinpoint.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/Joinpoint.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/MethodInterceptor.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/MethodInterceptor.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:org/aopalliance/intercept/MethodInvocation.class
[error] /Users/benjamingeer/.ivy2/cache/org.springframework/spring-aop/jars/spring-aop-4.3.12.RELEASE.jar:org/aopalliance/intercept/MethodInvocation.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/MergeReaderWrapper.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/MergeReaderWrapper.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$1.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$1.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$2.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$2.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$3.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$3.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$DocComparator.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$DocComparator.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$DocMap.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$DocMap.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter$DocValueSorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter$DocValueSorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/Sorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/Sorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingBinaryDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingBinaryDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingBits.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingBits.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum$DocFreqSorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum$DocFreqSorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingDocsEnum.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingFields.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingFields.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingNumericDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingNumericDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum$DocOffsetSorter.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum$DocOffsetSorter.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingPostingsEnum.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedNumericDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedNumericDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedSetDocValues.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingSortedSetDocValues.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingTerms.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingTerms.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader$SortingTermsEnum.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader$SortingTermsEnum.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/index/SortingLeafReader.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/index/SortingLeafReader.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector$1.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector$1.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.1.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector.class
[error] /Users/benjamingeer/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-5.5.4.jar:org/apache/lucene/search/EarlyTerminatingSortingCollector.class
[error] deduplicate: different file contents found in the following:
[error] /Users/benjamingeer/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.6.jar:org/joda/time/base/BaseDateTime.class
[error] /Users/benjamingeer/.ivy2/cache/org.elasticsearch/elasticsearch/jars/elasticsearch-2.4.6.jar:org/joda/time/base/BaseDateTime.class
[error] Total time: 27 s, completed 15-May-2018 15:28:39
```

I added that dependency because I need `rdf4j-rio-jsonld`. I tried adding a dependency just on that library, but for some reason, the Scala complier still couldn't find it. When I added the dependency on the whole `rdf4j-runtime`, the Scala compiler found the classes I needed. But now there seems to be a conflict with some other dependencies, but I don't understand why.

**Comment by benjamingeer** [comment]
There's a workaround in #851.
