### ISSUE TITLE
Create a custom standoff mapping 

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#903]
Hi,
I try to create a standoff mapping for our project following the steps of this [doc](https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#creating-a-custom-mapping). 
When I send my [data](https://github.com/dhlab-basel/Knora/files/2122849/data.xml.zip) with a bulk import : 
```
curl -u lumieres@unil.ch:test -X POST -d @data.xml http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0113
```
I get this error:
```json
{
    "status": 4,
    "error": "net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 13; columnNumber: 39; Element type \"xsl:template\" must be followed by either attribute specifications, \">\" or \"/>\"."
}
```
1/ do I have to provide a style sheet related to my mapping, is that the problem ?
2/ is the mapping replace or extend the default existing mapping ?

thx for your help

---

My test case is the following:
```html
<text xmlns="">
 <p>test p tag</p>
 <span class="sic" data-corr="Paris">paris</span>
</text>
```
`<p>` tag is already managed by the default mapping of Knora, so in my mapping I just have to map the `<span>` tag of class _sic_ and store the _data-corr_ string value (meaning a data fix): 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping>
    <mappingElement>
        <tag>
            <name>span</name>
            <class>sic</class>
            <namespace>noNamespace</namespace>
            <separatesWords>true</separatesWords>
        </tag>
        <standoffClass>            
            <classIri>http://www.knora.org/ontology/0113/lumieres-lausanne#StandoffEditionTag</classIri>
            <attributes>
                <attribute>
                    <attributeName>data-corr</attributeName>
                    <namespace>noNamespace</namespace>
                    <propertyIri>http://www.knora.org/ontology/0113/lumieres-lausanne#standoffEditionTagHasFix</propertyIri>
                </attribute>
            </attributes>
        </standoffClass>
    </mappingElement>
 </mapping>
```
```json
{
    "project_id": "http://rdfh.ch/projects/0113",
    "label": "LL Standoff mapping",
    "mappingName": "LLStandoffMapping"
}
```
```
curl -u lumieres@unil.ch:test -X POST -F json=@mappingForLL.json -F xml=@mappingForLL.xml  http://localhost:3333/v1/mapping
```
The custom standoff class:
```turtle
lumieres-lausanne:standoffEditionTagHasFix rdf:type owl:DatatypeProperty ;
                  knora-base:subjectClassConstraint lumieres-lausanne:StandoffEditionTag ;
                  knora-base:objectDatatypeConstraint xsd:string .

lumieres-lausanne:StandoffEditionTag rdf:type owl:Class ;
    rdfs:subClassOf knora-base:StandoffTag,
                   [
                      rdf:type owl:Restriction ;
                      owl:onProperty lumieres-lausanne:standoffEditionTagHasFix ;
                      owl:cardinality "1"^^xsd:nonNegativeInteger
                   ] ;
    rdfs:label "Represents an edition fix in a TextValue"@en.     
```

**Comment by tobiasschweizer** [comment]
In your mapping, you just define `<span class="sic">`. You  also have to define the other elements you are using, referring to the standard standoff entities. The standard mapping just handles everything supported for CkEditor and it s hard-coded in the old Salsah GUI.

> 2/ is the mapping replace or extend the default existing mapping ?

So yes, if you provide your own mapping, it has to have definitions for everything you are using.

> 1/ do I have to provide a style sheet related to my mapping, is that the problem ?

You may, but you do not have to. Default stylesheets are applied once XML has been produced from standoff. For example, you can create HTML that is then sent to the client.

Are you sure that the mapping is created correctly and that there is no default transformation indicated?

To me, it looks like if saxony tried to apply an XSLT which is syntactically wrong.

**Comment by gfoo** [comment]
No, I don't provide an xsl with the tag `<defaultXSLTransformation>` if it is what you are talking about. I also added all html tags from the default html mapping of Knora (mappingForStandardHTML.xml). 
[mappingForLL.xml.zip](https://github.com/dhlab-basel/Knora/files/2122973/mappingForLL.xml.zip)

The mapping seems to be created correctly: 
```json
{
    "mappingIri": "http://rdfh.ch/projects/0113/mappings/LLStandoffMapping",
    "status": 0
}
```
I'm going to check the content directly in graphdb.

**Comment by tobiasschweizer** [comment]
> No, I don't provide an xsl with the tag <defaultXSLTransformation> if it is what you are talking about.

Yes, exactly!

Thanks for the zip, I will check the mapping.

**Comment by tobiasschweizer** [comment]
The mapping looks good to me.

Just a guess: could you check that you use the correct mapping Iri in your bulk import for your text values?

**Comment by gfoo** [comment]
data attached in my first post (see above): 
```
        <p0113-lumieres-lausanne:hasBiography knoraType="richtext_value" mapping_id="http://rdfh.ch/projects/0113/mappings/LLStandoffMapping">
                <text xmlns="">
                <p>test p tag</p>
                <span class="sic" data-corr="Paris">paris</span>
                </text>
        </p0113-lumieres-lausanne:hasBiography>
```
```
lumieres-lausanne:hasBiography rdf:type owl:ObjectProperty ;
           rdfs:subPropertyOf knora-base:hasValue ;
           rdfs:label """Biographie"""@fr ;
           rdfs:comment """Informations  sur  la  formation,  les  activités  publiques  et  privées  de  la  personne,  ses séjours  à  l’étranger."""@fr ;
           knora-base:subjectClassConstraint lumieres-lausanne:Person ;
           knora-base:objectClassConstraint knora-base:TextValue ;
		   salsah-gui:guiElement salsah-gui:Richtext .
```

**Comment by tobiasschweizer** [comment]
That looks fine too.

Are you working on a specific branch I could try?

Is there webapi console log output (stacktrace)?

**Comment by gfoo** [comment]
a specific branch of Knora ? no, the develop branch. If you are talking about my project, our git lab is internal only :-|  Our ontology if you want to make some tests: 
[lumieres-lausanne-onto.zip](https://github.com/dhlab-basel/Knora/files/2123146/lumieres-lausanne-onto.zip)

(To reproduce, all my curl commands are in the previous posts above)

Trace: 
```
webapi ----------------------------------------------------------------
webapi Knora API Server started at http://0.0.0.0:3333
webapi ----------------------------------------------------------------
webapi[ERROR] Error on line 13 column 52
webapi[ERROR]   SXXP0003: Error reported by XML parser: Element type "xsl:template" must be followed by
webapi[ERROR]   either attribute specifications, ">" or "/>".
webapi [2018-06-21 12:20:37,713] ERROR - KnoraService(akka://webapi) - Unable to run route /v1/resources/xmlimport/http:%2F%2Frdfh.ch%2Fprojects%2F0113
webapi net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 13; columnNumber: 52; Element type "xsl:template" must be followed by either attribute specifications, ">" or "/>".
webapi 	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:862)
webapi 	at org.knora.webapi.util.standoff.XMLToStandoffUtil.xml2TextWithStandoff(XMLToStandoffUtil.scala:410)
webapi 	at org.knora.webapi.util.standoff.StandoffTagUtilV2$.convertXMLtoStandoffTagV2(StandoffTagUtilV2.scala:250)
webapi 	at org.knora.webapi.routing.RouteUtilV1$.$anonfun$convertXMLtoStandoffTagV1$2(RouteUtilV1.scala:217)
webapi 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
webapi 	at scala.util.Success.map(Try.scala:209)
webapi 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
webapi 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
webapi 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
webapi 	at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:60)
webapi 	at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
webapi 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
webapi 	at kamon.scala.instrumentation.FutureInstrumentation.$anonfun$aroundExecution$1(FutureInstrumentation.scala:46)
webapi 	at kamon.Kamon$.withContext(Kamon.scala:120)
webapi 	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:46)
webapi 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:59)
webapi 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
webapi 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi 	at kamon.executors.Executors$InstrumentedExecutorService$$anon$7.run(Executors.scala:270)
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
webapi Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 13; columnNumber: 52; Element type "xsl:template" must be followed by either attribute specifications, ">" or "/>".
webapi 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:471)
webapi 	at net.sf.saxon.event.Sender.send(Sender.java:179)
webapi 	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:233)
webapi 	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:101)
webapi 	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:859)
webapi 	... 27 common frames omitted
webapi Caused by: org.xml.sax.SAXParseException: Element type "xsl:template" must be followed by either attribute specifications, ">" or "/>".
webapi 	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
webapi 	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
webapi 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
webapi 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
webapi 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
webapi 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
webapi 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
webapi 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
webapi 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:451)
webapi 	... 31 common frames omitted

```

**Comment by tobiasschweizer** [comment]
It seems to happen here:

https://github.com/dhlab-basel/Knora/blob/1c385dc5ed0839f5f646abe7e64ab627e2c539d8/webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala#L401-L425

Could you print out the `XSLT`?

**Comment by gfoo** [comment]
```xsl
 <?xml version="1.0" encoding="UTF-8"?>

 <xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">

     <xsl:output indent="no" encoding="UTF-8"/>

     <xsl:template match="@*|node()">
         <xsl:copy>
             <xsl:apply-templates select="@*|node()"/>
         </xsl:copy>
     </xsl:template>

     <xsl:template match="tbody|pre|ol|span[@class="sic"]|hr|h4|h3|li|br|ul|code|h2|td|tr|cite|blockquote|p|h6|h1|h5|table">
         <xsl:variable name="ele" select="name()"/>

         <xsl:element name="{$ele}">
         <xsl:copy-of select="@*"/>
             <xsl:apply-templates/>
         </xsl:element>
         <xsl:text> </xsl:text>
     </xsl:template>

 </xsl:transform>
```

**Comment by tobiasschweizer** [comment]
`<xsl:template match="tbody|pre|ol|span[@class="sic"]|hr|h4|h3|li|br|ul|code|h2|td|tr|cite|blockquote|p|h6|h1|h5|table">`

The problem is that `"sic"` has double quotes, it should have single quotes instead.

**Comment by gfoo** [comment]
yes, just tried in oxygen editor, possible fix :
`span[@class=&quot;sic\\&quot;]`

**Comment by tobiasschweizer** [comment]
@gfoo This is surely not your fault. It seems to be a bug that we have to fix.

As a workaround, set `<separatesWords>` to false for the `<span class="sic">`

**Comment by tobiasschweizer** [comment]
@benjamingeer Shall we fix this together? Next week?

**Comment by benjamingeer** [comment]
@tobiasschweizer I could try to help, but I think you're the only one who understands that code. I really have no idea what it does.

**Comment by tobiasschweizer** [comment]
```
case class XMLTagSeparatorRequired(maybeNamespace: Option[String], tagname: String, maybeClassname: Option[String]) {

    // generate an XPath expression to match this element
    def toXPath = {

        val prefix: String = maybeNamespace match {
            case Some(namespace) => namespace + ":"
            case None => ""
        }

        val classSelector: String = maybeClassname match {
            case Some(classSel) => s"""[@class=\"$classSel\"]"""
            case None => ""
        }

        // the XPath expression matching this element
        s"$prefix$tagname$classSelector"
    }
}
```
Probably it just needs single quotes.

I think you wrote this ;-)

**Comment by benjamingeer** [comment]
I'm sure I've never worked on any of the code that deals with XML-to-standoff mappings. You wrote all that code:

https://github.com/dhlab-basel/Knora/commits/develop/webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala

**Comment by gfoo** [comment]
in any cases, the fix works for me :)

**Comment by gfoo** [comment]
(no hurry for me for this fix)

**Comment by tobiasschweizer** [comment]
@benjamingeer Ok, git blame balmes me: https://github.com/dhlab-basel/Knora/blame/1c385dc5ed0839f5f646abe7e64ab627e2c539d8/webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala#L223 :-) Sorry!

I am deeply ashamed and won't eat any ice cream until this is done :-)

**Comment by benjamingeer** [comment]
> I am deeply ashamed and won't eat any ice cream until this is done

When you're done you can run `git icecream` :)

**Comment by tobiasschweizer** [comment]
I ran `git vommit` once. No joke!
