### ISSUE TITLE
Knora crashes during import load test

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Knora#932]
Running the `load_test` from https://github.com/dhlab-basel/knora-tests crashes Knora. This should never happen. If something goes wrong, then a request can return an error, but Knora should keep on running.

**Comment by tobiasschweizer** [comment]
@subotic These are just a few ideas that could help find the problem:

- actor pool: monitoring actors for each router
- check configuration of routes and responders
- monitor HTTP connections (also the ones Knora opens to communicate with Sipi or the triplestore)
- check handling of files (e.g., the ones that are written to the temporary directory)

Maybe it could also be helpful for debugging to run Knora inside IntelliJ. However, compilation fails:

<img width="803" alt="compilation_bug" src="https://user-images.githubusercontent.com/6000023/42617722-efa5c8b6-85b2-11e8-99e2-5e159e834a3d.png">

I believe that this bug was already fixed. Do I need to flush an earlier build in IntelliJ?

**Comment by benjamingeer** [comment]
If the diagnosis in https://github.com/dhlab-basel/Knora/issues/741#issuecomment-394997229 is correct, possible solutions would be:

1. Upgrade to the latest version of akka-http.
2. If that doesn't work, consider not using the akka-http client API in `HttpTriplestoreConnector`, and switch to something like the [Apache HttpClient](https://hc.apache.org/httpcomponents-client-ga/) Java library instead.

**Comment by subotic** [comment]
After the refactoring of the `Authenticator` the real reason for the crash is a bit more evident:

```
webapi KnoraService - startupTaskRunner finished
webapi [2018-07-13 12:19:17,735] ERROR - Dispatcher - Triplestore responded with HTTP code 503 Service Unavailable: Query interrupted: Query evaluation took too long (HTTP status 503)
webapi
webapi org.knora.webapi.TriplestoreResponseException: Triplestore responded with HTTP code 503 Service Unavailable: Query interrupted: Query evaluation took too long (HTTP status 503)
webapi
webapi 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.$anonfun$getTriplestoreHttpResponse$5(HttpTriplestoreConnector.scala:601)
webapi 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
webapi 	at scala.util.Success.map(Try.scala:209)
webapi 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
webapi 	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
webapi 	at scala.concurrent.Future.map(Future.scala:289)
webapi 	at scala.concurrent.Future.map$(Future.scala:289)
webapi 	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
webapi 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector.$anonfun$getTriplestoreHttpResponse$3(HttpTriplestoreConnector.scala:598)
webapi 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
webapi 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
webapi 	at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:60)
webapi 	at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
webapi 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
webapi 	at kamon.scala.instrumentation.FutureInstrumentation.$anonfun$aroundExecution$1(FutureInstrumentation.scala:46)
webapi 	at kamon.Kamon$.withContext(Kamon.scala:120)
webapi 	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:46)
webapi 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:59)
webapi 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
webapi 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi 	at kamon.executors.Executors$InstrumentedExecutorService$$anon$7.run(Executors.scala:270)
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

It seems that GraphDB is having a hiccup. After the import script stopped, I could start it up again and it would work:

```
+++++++++++
88
http://www.ub.unibas.ch/digi/bez/bernoullibriefe/jpg/L_Ia_659/BAU_5_000055906_0001.jpg -> images/000055906/image/1042396.tif
http://www.ub.unibas.ch/digi/bez/bernoullibriefe/jpg/L_Ia_659/BAU_5_000055906_0002.jpg -> images/000055906/image/1042397.tif
http://www.ub.unibas.ch/digi/bez/bernoullibriefe/jpg/L_Ia_659/BAU_5_000055906_0003.jpg -> images/000055906/image/1042395.tif
http://www.ub.unibas.ch/digi/bez/bernoullibriefe/jpg/L_Ia_659/BAU_5_000055906_0004.jpg -> images/000055906/image/1042399.tif
http://www.ub.unibas.ch/digi/bez/bernoullibriefe/jpg/L_Ia_659/BAU_5_000055906_0005.jpg -> images/000055906/image/1042400.tif
http://www.ub.unibas.ch/digi/bez/bernoullibriefe/jpg/L_Ia_659/BAU_5_000055906_0006.jpg -> images/000055906/image/1042401.tif
http request failed:
1704-01-26_Bernoulli_Johann_I-Hermann_Jacob
500
{"status":4,"error":"org.knora.webapi.TriplestoreResponseException: Triplestore responded with HTTP code 503 Service Unavailable: Query interrupted: Query evaluation took too long (HTTP status 503)\n"}%                                                   [load_test] ./run.py                                                                                                                                                                                                                                 master
http request failed:
400
Creating letters (without text)
0
1
2
3
4
5
6
```


So now Knora is not crashing anymore.

**Comment by benjamingeer** [comment]
The GraphDB repository config sets a maximum query evaluation time of 5 seconds. Perhaps we should increase this?

```
owlim:query-timeout "5" ;
```

**Comment by tobiasschweizer** [comment]
@subotic Great that you found the reason of the problem!

@benjamingeer Yes, this might be necessary. What is a reasonable setting?

**Comment by benjamingeer** [comment]
> What is a reasonable setting?

How long is a piece of string?

https://en.wiktionary.org/wiki/how_long_is_a_piece_of_string

**Comment by tobiasschweizer** [comment]
@benjamingeer :-) 

At least I can increase the timeout locally when doing imports.

**Comment by subotic** [comment]
Opened a new issue #937 for the GraphDB timeout.
