### ISSUE TITLE
Exceeded configured max-open-requests value

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Knora#972]
On branch `fix/971-import-seqnum`:

```
sbt:webapi> testOnly *ResourcesV1R2RSpec
[info] ResourcesV1R2RSpec:
[info] The Resources Endpoint
[ERROR] Dispatcher - Failed to connect to triplestore
org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:249)
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:634)
	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:632)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:392)
	at scala.concurrent.Future$$Lambda$605/323571396.apply(Unknown Source)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.Promise$$Lambda$173/883000798.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$769/1526227791.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [64]. This means that the request queue of this pool (HostConnectionPoolSetup(localhost,7200,ConnectionPoolSetup(ConnectionPoolSettings(16,0,3,64,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.1.3),9999 milliseconds,119999 milliseconds,512,None,WebSocketSettings(<function0>,ping,Duration.Inf,akka.http.impl.settings.WebSocketSettingsImpl$$$Lambda$538/1229223741@4948d5b6),List(),ParserSettings(2048,16,1024,64,8192,64,8388608,256,2097152,Strict,RFC6265,true,Set(),Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,true,akka.util.ConstantFun$$$Lambda$354/950481112@2ab3d268,akka.util.ConstantFun$$$Lambda$354/950481112@2ab3d268,akka.util.ConstantFun$$$Lambda$360/1284674247@255947ed),None,TCPTransport),New,1 second),akka.http.scaladsl.HttpConnectionContext$@27e67564,akka.event.MarkerLoggingAdapter@3c0b2a59))) has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information.
	at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:88)
```

**Comment by subotic** [comment]
https://doc.akka.io/docs/akka-http/current/client-side/pool-overflow.html#pool-overflow-and-the-max-open-requests-setting

**Comment by benjamingeer** [comment]
Most of the requests look like this:

```sparql
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix knora-base: <http://www.knora.org/ontology/knora-base#>

SELECT ?s ?p ?o



    FROM <http://www.ontotext.com/explicit>


WHERE {
    ?s rdf:type knora-base:DefaultObjectAccessPermission .
    ?s knora-base:forProject <http://rdfh.ch/projects/0001> .

    
        ?s knora-base:forGroup <http://www.knora.org/ontology/knora-base#ProjectAdmin> .
    

    
        OPTIONAL { ?s knora-base:forResourceClass ?class } .
        FILTER ( !bound(?class) )
    

    
        OPTIONAL { ?s knora-base:forProperty ?prop } .
        FILTER ( !bound(?prop) )
    

    ?s ?p ?o .
}
```

I tried changing the end of `HttpTriplestoreConnector.getTriplestoreHttpResponse` to do this:

```scala
val recoveredTriplestoreResponse = triplestoreResponseFuture.recover {
    case tre: TriplestoreResponseException => throw tre
    case e: Exception => throw TriplestoreConnectionException("Failed to connect to triplestore", e, log)
}

Future(Await.result(recoveredTriplestoreResponse, 2.minutes))
```

It runs for a while, then hangs, then a request times out after 2 minutes.

**Comment by benjamingeer** [comment]
Caching default access permissions when they're requested doesn't work, because:

1. A lot of threads (more than 64) simultaneously request the same permission.
2. Each or them simultaneously finds that it's not in the cache, queries it in the triplestore, and adds it to the cache.

I think permission caching would have to work like ontology caching: all the permissions would be read from the triplestore and cached on startup, and the cache would be updated only when permissions are changed in the triplestore. Then requests would only return permissions from the cache, never from the triplestore.

**Comment by benjamingeer** [comment]
Blocking in `HttpTriplestoreConnector.getTriplestoreHttpResponse` freezes even if I increase the number of threads in `knora-ask-dispatcher`.

**Comment by benjamingeer** [comment]
I was doing the blocking wrong, now I think I have a solution...

**Comment by benjamingeer** [comment]
I think I figured out how to do it: make all methods in `HttpTriplestoreConnector` return `Try` instead of `Future`. When getting a `Future` from Akka HTTP, block until it's ready, then get its `Try`. I think this should ensure that we never have more connections than instances of `HttpTriplestoreConnector`. This seems to work with the bulk import example from #971.

**Comment by benjamingeer** [comment]
This seems to be fixed in #973, but I'm not sure how to make a test for it.

**Comment by subotic** [comment]
on the current `develop` without the fix we get the exception after more than 37 concurrent requests. This is the result of `ab` with the highest number of concurrent requests before we run into the error:

```
ab -n 37 -c 37 http://localhost:3333/v1/resources/http%3A%2F%2Frdfh.ch%2F047db418ae06
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        akka-http/10.1.3
Server Hostname:        localhost
Server Port:            3333

Document Path:          /v1/resources/http%3A%2F%2Frdfh.ch%2F047db418ae06
Document Length:        8185 bytes

Concurrency Level:      37
Time taken for tests:   1.535 seconds
Complete requests:      37
Failed requests:        0
Total transferred:      312909 bytes
HTML transferred:       302845 bytes
Requests per second:    24.10 [#/sec] (mean)
Time per request:       1535.059 [ms] (mean)
Time per request:       41.488 [ms] (mean, across all concurrent requests)
Transfer rate:          199.06 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.3      1       2
Processing:   343  620 166.8    659     837
Waiting:      342  620 166.7    658     836
Total:        344  621 166.6    660     837

Percentage of the requests served within a certain time (ms)
  50%    659
  66%    729
  75%    801
  80%    809
  90%    824
  95%    837
  98%    837
  99%    837
 100%    837 (longest request)
```

**Comment by subotic** [comment]
On the branch with the fix:

37 concurrent users
---
```
ab -n 37 -c 37 http://localhost:3333/v1/resources/http%3A%2F%2Frdfh.ch%2F047db418ae06
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        akka-http/10.1.3
Server Hostname:        localhost
Server Port:            3333

Document Path:          /v1/resources/http%3A%2F%2Frdfh.ch%2F047db418ae06
Document Length:        8185 bytes

Concurrency Level:      37
Time taken for tests:   1.474 seconds
Complete requests:      37
Failed requests:        0
Total transferred:      312909 bytes
HTML transferred:       302845 bytes
Requests per second:    25.10 [#/sec] (mean)
Time per request:       1473.933 [ms] (mean)
Time per request:       39.836 [ms] (mean, across all concurrent requests)
Transfer rate:          207.32 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2   0.6      2       3
Processing:   168  532 204.2    586     801
Waiting:      168  532 204.2    586     801
Total:        170  534 203.7    588     801

Percentage of the requests served within a certain time (ms)
  50%    578
  66%    673
  75%    700
  80%    728
  90%    786
  95%    800
  98%    801
  99%    801
 100%    801 (longest request)
```

100 concurrent users
---
```
ab -n 100 -c 100 http://localhost:3333/v1/resources/http%3A%2F%2Frdfh.ch%2F047db418ae06
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient).....done


Server Software:        akka-http/10.1.3
Server Hostname:        localhost
Server Port:            3333

Document Path:          /v1/resources/http%3A%2F%2Frdfh.ch%2F047db418ae06
Document Length:        8185 bytes

Concurrency Level:      100
Time taken for tests:   1.941 seconds
Complete requests:      100
Failed requests:        0
Total transferred:      845700 bytes
HTML transferred:       818500 bytes
Requests per second:    51.53 [#/sec] (mean)
Time per request:       1940.560 [ms] (mean)
Time per request:       19.406 [ms] (mean, across all concurrent requests)
Transfer rate:          425.59 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    6   2.1      6       9
Processing:    72 1002 503.8   1012    1868
Waiting:       61 1002 504.1   1011    1868
Total:         72 1008 502.0   1017    1871

Percentage of the requests served within a certain time (ms)
  50%   1017
  66%   1355
  75%   1477
  80%   1535
  90%   1690
  95%   1734
  98%   1791
  99%   1871
 100%   1871 (longest request)
```

**Comment by benjamingeer** [comment]
So basically it's no slower with the fix, and maybe even a bit faster.

**Comment by benjamingeer** [comment]
What if you increase the number of instances of `HttpTriplestoreConnector`?

**Comment by subotic** [comment]
Good idea. I will try it out tomorrow.
